name: Notificar Igor no PR

on:
  pull_request:
    types: [opened]

# 游뚿 A corre칞칚o CR칈TICA para o erro 403 Forbidden
permissions:
  contents: read # Permiss칚o padr칚o para ler o c칩digo
  issues: write # Permite que o Action crie coment치rios (em Issues e PRs)

jobs:
  notificar_colega:
    # Garante que o token de seguran칞a no job tenha as permiss칫es definidas acima.
    runs-on: ubuntu-latest
    steps:
      - name: Adicionar Coment치rio de Notifica칞칚o ao Colega
        # Usa a vari치vel GITHUB_TOKEN que agora tem permiss칚o de issues: write
        uses: actions/github-script@v6
        with:
          script: |
            const reviewer = 'IGOR-222222';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `游녦 Ol치, @${reviewer}! O Pull Request #${context.issue.number} foi aberto. Por favor, revise o Javadoc que documentei.`,
            });
